#!/usr/bin/env bash
set -euo pipefail

scene="addons/cogito/DemoScenes/COGITO_3_Lobby.tscn"
npc_scene="addons/cogito/DemoScenes/friendly_human_npc.tscn"
npc_script="addons/cogito/DemoScenes/friendly_human_npc.gd"

test -f "$npc_scene"
test -f "$npc_script"

grep -q 'name="FriendlyHumanNPC"' "$scene"
grep -q 'path="res://addons/cogito/DemoScenes/friendly_human_npc.tscn"' "$scene"
grep -q 'name="FriendlyHumanNPCPath"' "$scene"
grep -q 'name="HumanMeetingRoomStart"' "$scene"
grep -q 'name="HumanMeetingRoomDoorInside"' "$scene"
grep -q 'name="HumanMeetingRoomDoorOutside"' "$scene"
grep -q 'name="HumanLobbyExitLane"' "$scene"
grep -q 'name="HumanLobbyStairBypass"' "$scene"
grep -q 'name="HumanLobbyCenterApproach"' "$scene"
grep -q 'name="HumanMainLobbyCrossing"' "$scene"
grep -q 'name="HumanBreakRoomEntrance"' "$scene"
grep -q 'name="HumanBreakRoomVisit"' "$scene"
grep -q 'name="HumanSofaApproach"' "$scene"
grep -q 'name="HumanSofaStop"' "$scene"
grep -q 'route_root = NodePath("../FriendlyHumanNPCPath")' "$scene"
grep -q 'walk_speed = 0.35' "$scene"

grep -q 'type="CharacterBody3D"' "$npc_scene"
grep -q 'path="res://addons/cogito/DemoScenes/friendly_human_npc.gd"' "$npc_scene"
grep -q 'name="Visual"' "$npc_scene"
grep -q 'name="Body"' "$npc_scene"
grep -q 'name="Head"' "$npc_scene"
grep -q 'name="BasicInteraction"' "$npc_scene"
grep -q 'interaction_text = "Talk"' "$npc_scene"
grep -q 'name="NavigationAgent3D" type="NavigationAgent3D"' "$npc_scene"
grep -q 'navigation_agent = NodePath("NavigationAgent3D")' "$npc_scene"
grep -q '@export var navigation_agent: NavigationAgent3D' "$npc_script"
grep -q 'navigation_agent.target_position = target.global_position' "$npc_script"
grep -q 'navigation_agent.get_next_path_position()' "$npc_script"
grep -q 'velocity_computed.connect(_on_navigation_agent_velocity_computed)' "$npc_script"
grep -q 'func _on_navigation_agent_velocity_computed(safe_velocity: Vector3)' "$npc_script"
grep -q '@export var use_navigation_agent: bool = true' "$npc_script"
grep -q 'func _get_next_route_position(target: Node3D)' "$npc_script"
grep -q 'if not use_navigation_agent or navigation_agent == null:' "$npc_script"
grep -q 'navigation_agent.is_target_reachable()' "$npc_script"
grep -q '@export var navigation_probe_steps: int = 3' "$npc_script"
grep -q '@export var navigation_probe_step_distance: float = 0.35' "$npc_script"
grep -q 'func _is_navigation_path_clear(next_position: Vector3)' "$npc_script"
grep -q 'move_and_collide(probe_motion, true)' "$npc_script"
grep -q 'var using_navigation := next_position != target.global_position' "$npc_script"
grep -q '@export var auto_open_doors: bool = true' "$npc_script"
grep -q '@export var door_close_distance: float = 2.2' "$npc_script"
grep -q '@export var meeting_room_arrival_distance: float = 0.25' "$npc_script"
grep -q '@export var wait_at_route_points: bool = false' "$npc_script"
grep -q '@export var wait_time_min: float = 5.0' "$npc_script"
grep -q '@export var wait_time_max: float = 60.0' "$npc_script"
grep -q '@export var no_wait_route_point_names: Array\[String\] = \[' "$npc_script"
grep -q '@export var chair_search_distance: float = 2.0' "$npc_script"
grep -q '@export var allow_sitting: bool = false' "$npc_script"
grep -q '@export var sit_chair_parent_name: String = "MEETING_ROOM"' "$npc_script"
grep -q '@export var sit_route_point_names: Array\[String\] = \["HumanMeetingRoomStart"\]' "$npc_script"
grep -q 'func _open_nearby_doors()' "$npc_script"
grep -q 'door.open_door(self)' "$npc_script"
grep -q 'func _close_opened_doors()' "$npc_script"
grep -q 'door.close_door(self)' "$npc_script"
grep -q 'func _begin_route_wait(target: Node3D)' "$npc_script"
grep -q 'func _should_wait_at_route_point(target: Node3D)' "$npc_script"
grep -q 'if not wait_at_route_points:' "$npc_script"
grep -q 'if not _should_wait_at_route_point(target):' "$npc_script"
grep -q 'func _try_sit_nearby_chair()' "$npc_script"
grep -q 'func _can_sit_at_route_point(target: Node3D)' "$npc_script"
grep -q 'if not allow_sitting:' "$npc_script"
grep -q 'return sit_route_point_names.has(target.name)' "$npc_script"
grep -q 'func _is_node_inside_named_parent(node: Node, parent_name: String)' "$npc_script"
grep -q 'var _stand_position_before_sit := Vector3.ZERO' "$npc_script"
grep -q 'func _restore_standing_position_after_sit()' "$npc_script"
grep -q 'func _set_sitting_pose(is_sitting: bool)' "$npc_script"
grep -q 'avoidance_enabled = true' "$npc_scene"

if grep -q 'CogitoNPC/cogito_npc.tscn' "$npc_scene"; then
	echo "friendly_human_npc.tscn must not instance the robot NPC template" >&2
	exit 1
fi
